### ISSUE TITLE
NoneType not iterable (Beta)

### ISSUE THREAD

**Issue by e1ace** [hawky358/hass_ids_hyyp#16]
I decided to get test out the v1.4.0-b2 and have the following issue.

```
Logger: custom_components.ids_hyyp.coordinator
Source: custom_components/ids_hyyp/coordinator.py:35
Integration: IDS Hyyp (hawkMod) (documentation)
First occurred: 18:59:09 (2 occurrences)
Last logged: 18:59:33

Unexpected error fetching ids_hyyp data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ids_hyyp/coordinator.py", line 35, in _async_update_data
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/client.py", line 143, in load_alarm_infos
    return HyypAlarmInfos(self).status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/alarm_info.py", line 259, in status
    formatted_data: dict[Any, Any] = self._format_data()
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhyypapihawkmod/alarm_info.py", line 196, in _format_data
    for zone_state in zone_states["zones"]:
TypeError: 'NoneType' object is not iterable
```

I had deleted the integration before updating the version.

**Comment by e1ace** [comment]
Issue fixed with b3.

I don't mind helping with debug builds, let me know what you need.

**Comment by hawky358** [comment]
> I don't mind helping with debug builds, let me know what you need.

Hello,
The debug build is now on as 1.4.0-debug. This build does nothing except log information, so you can't "use" it as such.

To dump the logs, please look at the readme for step by step instructions.
Note that you need to log out of IDS and enable logging before logging in again. (Per screenshots)

[Readme](https://github.com/hawky358/hass_ids_hyyp/tree/1.4.0-debug#ids-hyyp-hawkmod)

- You should then a text file maybe ~300-600kb+.
- I need that file. This will let me see what information you're getting from IDS
   **PLEASE NOTE** You may want to "sanitize" the file as it contains the raw data from IDS which may include your email address, real name, physical address, etc. if you've added that into the IDS app. You can do a find and replace, just make info XXXXX or something.

**Comment by e1ace** [comment]
Done btw - any way to give this to you directly? Twitter DM maybe? I believe I've santized but tough to know if it's all clean.

**Comment by hawky358** [comment]
Hello, thanks.

You can send it to me on Discord, here's a server. If you join I'll give you permissions to join a private channel where you can share.
https://discord.gg/q6mxB5dn

Alternatively I've made an email box where you can send it.
tempmail31july@hawkweb.net
