### ISSUE TITLE
error logging in to ADT secure home - error referencing IDS HYYP

### ISSUE THREAD

**Issue by This-is-me-yes** [hawky358/hass_ids_hyyp#17]
[1.4.0-b3](https://github.com/hawky358/hass_ids_hyyp/releases/tag/1.4.0-b3)

Latest version not connecting to correct platform when selecting ADT I get the IDS HYYP referencing in the log 

ids_hyyp
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ids_hyyp/__init__.py", line 47, in async_setup_entry
hyyp_client = HyypClient(token=entry.data[CONF_TOKEN], pkg=entry.data[CONF_PKG], userid=entry.data[USER_ID])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HyypClient.__init__() got an unexpected keyword argument 'userid'
2023-07-28 20:59:11.277 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxxxx@xxxxxxxx.co.za for ids_hyyp
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ids_hyyp/__init__.py", line 47, in async_setup_entry
hyyp_client = HyypClient(token=entry.data[CONF_TOKEN], pkg=entry.data[CONF_PKG], userid=entry.data[USER_ID])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HyypClient.__init__() got an unexpected keyword argument 'userid'

**Comment by hawky358** [comment]
Hello,

I don't see anything that makes it seem like it not using the correct platform. 
It seems like for some reason it hasn't downloaded the correct API since the userid is something I added into the new API.

Can you check if you remove the integration and re-add it, restarting after each step?

**Comment by This-is-me-yes** [comment]
followed the steps u suggested same error 

I was expecting the secure home name be in the log not hyyp hence my thought of incorrect server ...  

2023-07-29 00:07:06.221 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@xxxxxxxx.co.za for  **_

> ids_hyyp

_**

But yes installed rebooted readied same error 

 File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ids_hyyp/__init__.py", line 47, in async_setup_entry
    hyyp_client = HyypClient(token=entry.data[CONF_TOKEN], pkg=entry.data[CONF_PKG], userid=entry.data[USER_ID])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HyypClient.__init__() got an unexpected keyword argument 'userid'
2023-07-29 00:06:55.812 ERROR (MainThread) [frontend.js.latest.202307051] http://homeassistant.local:8123/frontend_latest/27811-wBwLJM4buZA.js:1:78214 TypeError: this.contentElement is null
2023-07-29 00:07:06.221 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@xxxxxxxx.co.za for  ids_hyyp


Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ids_hyyp/__init__.py", line 47, in async_setup_entry
    hyyp_client = HyypClient(token=entry.data[CONF_TOKEN], pkg=entry.data[CONF_PKG], userid=entry.data[USER_ID])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HyypClient.__init__() got an unexpected keyword argument 'userid'

**Comment by hawky358** [comment]
Very peculiar.
The error doesn't really make sense since the HyypClient Class is designed to accept a userid argument. I specifically added it in the newer version of the API.

I wonder if the ADT version gives completely different data here which somehow breaks the Class. I can't fathom what though, since it should then give a different error.

Which was the last version that was working for you 1.3.4? 
I can make a debug version based on that if you want to send me new debug data to see what's the issue. Let me know. Otherwise you can stick with what's working.

It's quite difficult for me to support the ADT version since I don't have access to it and it seems that returns and features differ.
I can probably add a check to disable certain features for the ADT package since it doesn't seem to support it, but then there would be no point in you actually upgrading the version since it literally will have nothing new, you may as well stick with the latest working one.

Depending on what I see I may decide to remove the ADT package from future versions and just leave the latest working ADT version as a legacy version.

**Comment by This-is-me-yes** [comment]
Fixed the issue 

Reloaded my HA from scratch ..

**Comment by hawky358** [comment]
Hello,

Thanks for the feedback. That confirms my suspicions that the HA didn't install the API for some reason

Just out of interest, what are you using to run HA and were you messing around with dev settings and such?

I have seen someone running HA on a PI with an SD card that the actual HA updates fail.  The easiest option is to re-install and restore from backup. Haven't seen this specific issue though.

In any event, good to see it's working again.

**Comment by superbole** [comment]
I was also struggling to log in, found this issue and after reading did another restart after which I could log in. I had done all the restarts suggested in the installation instructions.
