### ISSUE TITLE
Issue logging in

### ISSUE THREAD

**Issue by LauranceW** [hawky358/hass_ids_hyyp#27]
Hi,

Every time I try and log in I get an error: "Unexpected error".  My user name and password are the same as I use on my android app for the HYYP.  Is there anything that I can do to fix this issue?

LauranceW
![image](https://github.com/user-attachments/assets/dcf8fd88-8f4c-42bf-b82b-78b8407ded6b)

**Comment by hawky358** [comment]
Hello,

This is related to google deprecating the FCM system. For now there is nothing you can do.

This may require a major rework of how push notifications work. I'll see if a library exists for the new v1 API.

If I can't get something out within a week or so I'll release a version without push-notifications as an interim measure.

**Comment by LauranceW** [comment]
Hello,

Thank you for the quick reply.

I really hope that there is a workaround.

**Comment by hawky358** [comment]
Can you try again please?

I've checked today, it seems like it may have been a temporary issue on google's side.  I can log in now on my test server.

I have a preliminary build which uses the V1 API which I am testing a bit, but I don't want to push anything if it's not yet required.

**Comment by LauranceW** [comment]
Good afternoon.
Thank you. I have managed to log in.

**Comment by hawky358** [comment]
Moved to new issue #28
