### ISSUE TITLE
Alarm won't arm via integration

### ISSUE THREAD

**Issue by hawky358** [hawky358/hass_ids_hyyp#32]
I've had some issues for the last few weeks where I just can't arm my alarm through HA - I was hoping this would find the issue. It works fine on the panel so I'm not sure if it's integration related. 

If I have a violated zone it gives back _{"failure_cause": "VIOLATED ZONES", "zones": {"1": "FRONT DR"}, "timestamp": 1728201775.0968704}_ - so I know that is working. When I try arm when it should be able to arm (no violations) I get _{"failure_cause": 0, "timestamp": 1728330676.017343}_.

Any ideas? I'm guessing not. I've tried removing and readding the integration.

_Originally posted by @e1ace in https://github.com/hawky358/hass_ids_hyyp/issues/30#issuecomment-2399778113_

**Comment by e1ace** [comment]
[home-assistant_ids_hyyp_2024-10-08T13-51-45.338Z.log](https://github.com/user-attachments/files/17294504/home-assistant_ids_hyyp_2024-10-08T13-51-45.338Z.log)

[home-assistant_ids_hyyp_2024-10-08T14-13-31.644Z.log](https://github.com/user-attachments/files/17294707/home-assistant_ids_hyyp_2024-10-08T14-13-31.644Z.log)

1.  I tried sanitizing with xxxxxxxxxxxxxx where applicable. If you think I've missed something private let me know. I also didn't clear - I just deleted the warnings/errors. I see that when trying to turn a zone off it says "Code required to bypass zone". But I've configured the code and I've definitely entered it correctly.

![image](https://github.com/user-attachments/assets/7d9428ff-ff5f-40ca-9f5c-535e4de8072a)

![image](https://github.com/user-attachments/assets/cdc0dade-4372-49f5-b7c9-fbb38c068196)

2. Yes. IDS arming works.

**Comment by hawky358** [comment]
Very strange, that it "lets one through eventually" ...
I see you've in the past had some unique errors which I can't/couldn't explain so I implemented workarounds.
There is something unique about your setup which somehow doesn't always want to work with the normal IDS API.

I will be very difficult for me to debug without having better access e.g. seeing what your APP is doing differently.

**Comment by e1ace** [comment]
Yeah - the other issues were the fact that I had two sites on the app. I now only have one.

I don't mind sharing more details with you if you require it (and you want to assist 😅)

**Comment by hawky358** [comment]
You also had 2 sites?  Someone else actually brought that bug to my attention and I fixed that.
You had some other errors, but I can't recall exactly what the issue was back then.

It's still quite odd that this only occurs with "actions", you obviously receive the status data and such...

In any event...

The best way for me to get direct data is access to your IDS. 
There is a "safe" way to do this:

- I create a temporary HYYP account.
- You add that account as a user to your HYYP app
- You can add a temporary PIN to your panel

We can coordinate on discord as to when I can "test".
Once I'm done you delete that user from the app, and remove the PIN. This way I never have access to your credentials and you have control of access.
I normally do this when people come visit me and I want to allow them "free access" to come and go when I'm not there, then remove them when they leave.

That all being said, if you're not comfortable with this, please don't do it. It's completely understandable.  I just don't have another "easy" way right now.
The alternative is that you'll have to use the python API directly and see whether you can find something that seems odd. Also capture traffic from your phone (IDS app) so I can analyse that to see if there's something different.  You'll need to do a MITM with SSL root for this.  It's "easier" on ios, I think the android app has SSL pinning implemented even with another root cert installed, though I haven't tried on emulators and such.

**Comment by hawky358** [comment]
I've managed to get a MITM working on the android version.
I don't see anything different during the arm/disarm/bypass process, still uses the same methods.

I don't know why your setup is doing this.

Can you try adding another pin onto your panel then using that pin?

**Comment by hawky358** [comment]
@e1ace , I've released 1.8.0b10 which should help you figure out the issue as this information comes directly from IDS.

See [this ](https://github.com/hawky358/hass_ids_hyyp/issues/30#issuecomment-2405898498) comment.

**Comment by hawky358** [comment]
Before you default your panel and all that, check what  the new (1.8.0b10) `sensor.[site]_arm_failure_cause` shows when you try to arm.

**Comment by hawky358** [comment]
Have you been able to figure out your issue?

**Comment by e1ace** [comment]
I've been to worried about defaulting my alarm system. You can close the
ticket. I'll get to it some day.

**Comment by hawky358** [comment]
Ok,

You can try 1.8.2rc1 and check `sensor.[site]_arm_failure_cause` to see if you learn something. This sensor is what ids says is wrong with the request.

I'd hold off defaulting the panel, maybe just re-add the ids module?
